[build]
command = "npm run build"
pages_build_output_dir = "dist"

[site]
bucket = "./public"

[env.production]
name = "daily-recipe"

# KV 绑定
[[kv_namespaces]]
binding = "RECIPES_KV"
id = "d64e1a0e5c04420f96561e2c91df2893"

# R2 存储桶
[[r2_buckets]]
binding = "RECIPE_IMAGES"
bucket_name = "recipe"

# 环境变量
[vars]
ENVIRONMENT = "production"

# 需要在Cloudflare Dashboard中设置的加密环境变量
# - GROQ_API_KEY: Groq API密钥
# - JWT_SECRET: JWT签名密钥 